# Generated by Django 3.2 on 2024-01-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240119_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.manager'),
        ),
    ]
